update Dockerfile for webapp

diff --git a/frontend/web-app/Dockerfile b/frontend/web-app/Dockerfile
--- a/frontend/web-app/Dockerfile
+++ b/frontend/web-app/Dockerfile
@@ -1,33 +1,45 @@
-FROM node:18-alpine AS deps
+FROM node:18-alpine AS base
+
+FROM base AS deps
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-COPY frontend/web-app/package*.json ./
-RUN  npm install --omit-dev
+COPY frontend/web-app/package.json frontend/web-app/yarn.lock* frontend/web-app/package-lock.json* frontend/web-app/pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-FROM node:18-alpine AS builder
+FROM base AS builder
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY frontend/web-app ./
 
 ENV NEXT_TELEMETRY_DISABLED 1
 
-RUN npm run build
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# production image, copy all files and run next
-FROM node:18-alpine AS runner
+
+FROM base AS runner
 WORKDIR /app
 
 ENV NODE_ENV production
-
 ENV NEXT_TELEMETRY_DISABLED 1
 
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
 
 COPY --from=builder /app/public ./public
-COPY --from=builder /app/package.json ./package.json
-COPY --from=builder /app/next.config.js ./next.config.js
+
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
 
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
